title: zotregistry.io
description: A vendor-neutral OCI image registry server purely based on OCI Distribution Specification
github:
  repository_url: https://github.com/project-zot/zot
theme: jekyll-theme-tactile
